### ISSUE TITLE
Great Plugin but performance?

### ISSUE THREAD

**Issue by Beebster-UK** [D0RYU/TemplateSaver#1]
Thanks for writing such clever plugin. I literally groan when I have recreate / copy scenes I want to reuse from previous projects so this is great step in the right direction.

My only hope is that the load and save performance when the templated scene is re-imported to a new project can be improved. To overcome this I guess I could ensure the template is bare bones i.e. no audio or gfx embedded as I guess this is what's causing the delay?

Depsite the performance I must say it works without error on both my Windows and Mac desktop.

**Comment by Beebster-UK** [comment]
Update:

Culprit was actually a .wave audio file I had embedded in the original scene. Once the templated scene had imported I just saved the audio as .sample resource and now the scene runs like the original before I added as template.

**Comment by D0RYU** [comment]
> Update:
> 
> Culprit was actually a .wave audio file I had embedded in the original scene. Once the templated scene had imported I just saved the audio as .sample resource and now the scene runs like the original before I added as template.

hey! sorry for getting back to you so late haha
I just recently started working on the addon again, so if you still got any issues just lmk and I can look into them
glad that you got your problem fixed though!
